kind: ConfigMap
apiVersion: v1
metadata:
  name: blazorclient-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: blazorclient
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  #ApiGatewayUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30050
  #IdentityUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30008
  ApiGatewayUrlExternal: http://apigateway.{{ .Values.externalDnsNameOrIP}}
  IdentityUrlExternal: http://identity-api.{{ .Values.externalDnsNameOrIP}}
  ApplicationInsights__InstrumentationKey: {{ .Values.servicesInstrumentationKey}}

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: blazorclient
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: blazorclient
spec:
  replicas: 1
  selector:
    matchLabels:
      service: blazorclient
  template:
    metadata:
      labels:
        app: eshop
        service: blazorclient
    spec:
      containers:
        - name: blazorclient
          image: eshopdapr/blazor.client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: blazorclient-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

kind: Service
apiVersion: v1
metadata:
  name: blazor-client
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: blazorclient
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    service: blazorclient

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blazor-client
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: eshopondapr.{{ .Values.externalDnsNameOrIP}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: blazor-client
            port: 
              number: 80