apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendmail
  namespace: {{ .Values.namespace }}
spec:
  type: bindings.smtp
  version: v1
  metadata:
  - name: host
    value: mailserver
  - name: port
    value: 25
  - name: user
    secretKeyRef:
      name: SmtpUser
      key: SmtpUser
  - name: password
    secretKeyRef:
      name: SmtpPassword
      key: SmtpPassword
  - name: skipTLSVerify
    value: true
auth:
  secretStore: eshop-kvsecretstore
scopes:
  - ordering-api
